# Generated by Django 3.1.7 on 2021-03-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='display_name',
            new_name='username',
        ),
    ]
